### ISSUE TITLE
Crater casing is wrong, papercut when reproducing diffs

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontc#1010]
Crater lists `Moirai/sources/Moirai.glyphs` but the correct path (in https://github.com/JAMO-TYPEFACE/Moirai) is `Moirai/Sources/moirai.glyphs`

**Comment by cmyr** [comment]
ah, we're using the filename listed in `config.yaml` (which is `morai.glyphs`) and then we're hardcoding `sources`.

**Comment by cmyr** [comment]
fixed a while ago
