### ISSUE TITLE
`name` records for copyright notice, manufacturer name, and designer (0, 8, 9) aren't created by fontc

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontc#1011]
Occurs for _at least_:

1. [Moirai/sources/Moirai.glyphs](https://github.com/JAMO-TYPEFACE/Moirai)
2. [BagelFat/sources/BagelFat.glyphs](https://github.com/JAMO-TYPEFACE/BagelFat)

This appears to be caused by use of `language = ENG` on the records in question. For example given the input below (from BagelFat)copyright and manufacturer will not copy but manufacturerURL and licenses will:

```
properties = (
{
key = copyrights;
values = (
{
language = ENG;
value = "Copyright 2022 The Bagel Fat Project Authors (https://github.com/JAMO-TYPEFACE/BagelFat)";
}
);
},
{
key = manufacturers;
values = (
{
language = ENG;
value = JAMO;
}
);
},
{
key = manufacturerURL;
value = "https://jamo.works";
},
{
key = licenses;
values = (
{
language = dflt;
value = "This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: https://scripts.sil.org/OFL";
}
);
},
```

#187 added support for language dflt, perhaps we merely need to accept ENG as well. One wonders what fontmake does in the face of an entry for both ENG and dflt. EDIT: it seems like it just takes the first value absent a dflt. For example, FRST is chosen here:

```
{
key = manufacturers;
values = (
{
language = ONE;
value = FRST;
},
{
language = TWO;
value = SCND;
},
);
},
```

If a dft is present it is preferred, "dflt value" is selected for:

```
{
key = licenses;
values = (
{
language = ENG;
value = "ENG value";
},
{
language = dflt;
value = "dflt value";
}
```

**Comment by anthrotype** [comment]
I think this is the logic you're trying to match:

```python
        for key in ["dflt", "default", "ENG"]:
            if key in self._localized_values:
                return self._localized_values[key]
        return list(self._localized_values.values())[0]
```

https://github.com/googlefonts/glyphsLib/blob/1cb4fc5ae2cf385df95d2b7768e7ab4eb60a5ac3/Lib/glyphsLib/classes.py#L3155-L3161
