### ISSUE TITLE
crater should skip sources that have multiple masters but `buildVariable` set to false

### ISSUE THREAD

**Issue by cmyr** [googlefonts/fontc#1073]
We should probably be skipping these files in both modes, but they are particularly obvious in gftools mode since they turn into compile failures.

Figuring out whether or not a source has multiple masters will involve actually loading the source, but that's probably something we were going to have to do anyway.

**Comment by rsheeter** [comment]
Per VC I don't think we should skip these, reporting them as failures is more or less correct
