### ISSUE TITLE
non-deterministic interpolation error

### ISSUE THREAD

**Issue by cmyr** [googlefonts/fontc#1146]
there's sime jitter on crater runs lately involving one particular font, which fails to compile some portion of the time.

repro with,

`python resources/scripts/ttx_diff.py 'https://github.com/ThomasJockin/readexpro#sources/ReadexPro.glyphs'`.

(it took me four tries to get a failure, but maybe you're luckier than I am?)

**Comment by cmyr** [comment]
Okay, so I think I've figured this out; it's a race condition related to nested components. When converting components to contours we need to make sure to perform this operation in order, i.e. if glyph A has component B has component C we need to make sure we convert B before A.

**Comment by rsheeter** [comment]
IIUC we shouldn't need ttx_diff, just run `$ cargo run -- ~/.fontc_crater_cache/ThomasJockin/readexpro/sources/ReadexPro.glyphs` over and over. Locally I'm seeing this fail on the order of 50% of the time on `main`.
