### ISSUE TITLE
contours with single point get different 'point type' vs fonttools (glyphs sources)

### ISSUE THREAD

**Issue by cmyr** [googlefonts/fontc#1173]
Or, at least for glyphs sources.

This is a silly issue, but here we go:

There is a glyph in 'IngridDarling' (`python resources/scripts/ttx_diff.py 'https://github.com/googlefonts/ingrid-darling#sources/IngridDarling.glyphs'`) that has a contour with only one point.

In the glyphs UI, this contour is an off-curve point.

We compile this contour and include it in the font, where it's point type is listed as offcurve.

`fontmake` also includes this useless contour, but there it ends up being labeled as 'oncurve'. I haven't tracked down why this is.

- this whole business is silly; is there any reason to even include these contours?
- if we  are including these contours, there's an argument that the single point should at least be 'oncurve', which has _some_ meaning; a single off-curve point seems completely meaningless?
- doing that would be easy and at least make us match, and would be simpler than fixing fontmake?
- why???

**Comment by rsheeter** [comment]
A single off-curve seems nonsensical ... but that is what's in the source iiuc. Unless there is a good reason to prefer oncurve perhaps we should just eliminate this in ttx_diff.

**Comment by cmyr** [comment]
okay I think normalizer makes sense for this. Would you like to put this on your "small things between meetings" list? Should get us an easy +1..

**Comment by rsheeter** [comment]
Sure I can take it
