### ISSUE TITLE
Support stylistic set names in legacy Glyphs form

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontc#1174]
```
{
code = "sub placeholder_siyaq by placeholder_siyaq.alt;";
name = ss01;
notes = "Name: Alternate placeholder";
},
```

Seems to generate a name in `python resources/scripts/ttx_diff.py 'https://github.com/notofonts/indic-siyaq-numbers#sources/NotoSansIndicSiyaqNumbers.glyphs'`

Edit: `$ python resources/scripts/ttx_diff.py 'https://github.com/googlefonts/beau-rivage#sources/BeauRivage-Pro.glyphs'` as well, likely others.

This appears to be the legacy stylistic set naming described at https://glyphsapp.com/learn/stylistic-sets#g-names-for-stylistic-sets.

**Comment by cmyr** [comment]
okay neat this looks to be used in 60+ fonts in the collection.
