### ISSUE TITLE
map between design, external, and internal coordinates correctly

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/fontc#22]
designspace coordinates can be interpreted using so-called user-space (e.g. fvar axis [min,default,max], or OT registered axes predefined ranges) or as internal design-space coordinates (arbitrary numbers convenient to designers for defining source locations).
Designspace axes contain a `<map>` elements to map from the former to the latter, and are the basis for defining the `avar` table that "bends" the default normalization process (the one mapping min to -1, default to 0 and max to +1 and lerp anything in between).

Currently we don't even parse these map elements and assume there's no such user vs design vs normalised space distinction. 

See https://github.com/googlefonts/fontmake-rs/pull/18#discussion_r1036400605

**Comment by rsheeter** [comment]
Copied from @anthrotype's note on https://github.com/googlefonts/fontmake-rs/pull/43#discussion_r1044468469:

> The master axis values in Glyphs are in internal design coordinates. The global axes definitions (the min/default/max that go in fvar, the .designspace axes min/default/max, and hence also our ir:Axis) are in user-space coordinates.
> The mapping between user-space to internal design-space coordinates is defined in Glyphs in multiple ways
> 
> directly via the "Axis Mappings" font custom parameter
> via "Axis Location" custom parameters set on each font master
> implicitly by deriving it for wght and wdth axis only from the user-space location of the instances
> it's one of the most complicated pieces of code in glyphsLib, for your amusement
> 
> https://github.com/googlefonts/glyphsLib/blob/f6e9c4a29ce764d34c309caef5118c48c156be36/Lib/glyphsLib/builder/axes.py#L155

I think we'll want explicit types so you cannot accidentally stick designspace coords in as userspace and vice versa.

**Comment by rsheeter** [comment]
https://github.com/googlefonts/glyphsLib/issues/280#issuecomment-374914714 appears to explain how to interpret "Axis Location": the mapping is 
> design locations = xxxValue and user locations = "Axis Location" parameter

**Comment by rsheeter** [comment]
#83 left out instances: https://github.com/googlefonts/fontmake-rs/pull/83#discussion_r1065795413

**Comment by rsheeter** [comment]
https://github.com/googlefonts/fontc/issues/918 tracks instances Axis Location. As that is not itself a mapping between coordinates issue I think we can close this.
