### ISSUE TITLE
Add rounding to deltas

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontc#235]
Add the test and fix from https://github.com/fonttools/fonttools/blob/3b9a73ff8379ab49d3ce35aaaaf04b3a7d9d1655/Tests/varLib/models_test.py#L167

If we do not have rounding within the delta computation we subtract delta(s) that will be applied to avoid double-application, but when applied they are rounded so we can accumulate rounding error from each delta.

**Comment by anthrotype** [comment]
also, note that when rounding deltas (e.g. see below for gvar) in fontTools we use the Python3 built-in `round` function, which uses Banker's rounding, whereby ties are rounded up or down towards the nearest even number:

https://github.com/fonttools/fonttools/blob/3b9a73ff8379ab49d3ce35aaaaf04b3a7d9d1655/Lib/fontTools/varLib/__init__.py#L286

This way of rounding is statistically better, and we tend to use in place of the otRound whenever we deal with abstract numbers that aren't visual absolute coordinates.
Also see @behdad's comment in https://github.com/fonttools/fonttools/pull/2214#issuecomment-790742479

I'm not sure if Rust has a direct equivalent for this, but we should probably match that for consistency with the python build pipeline.

**Comment by anthrotype** [comment]
the rust_decimal crate has https://docs.rs/rust_decimal/latest/rust_decimal/enum.RoundingStrategy.html#variant.MidpointNearestEven

**Comment by anthrotype** [comment]
and looks like the rust_decimal::Decimal::round method defaults to theBanker's method:

https://docs.rs/rust_decimal/latest/rust_decimal/struct.Decimal.html#method.round

**Comment by rsheeter** [comment]
https://github.com/rust-lang/rust/issues/96710 appears to be coming. We could likely do it ourselves and flip once that lands.

**Comment by anthrotype** [comment]
Fixed by #1070
