### ISSUE TITLE
Support per-glyph category/subCategory in .glyphs files

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontc#290]
https://github.com/googlefonts/fontmake-rs/issues/285#issuecomment-1553710896 notes:

> Yes, this and the category/subCategory set in the .glyphs files are the wayy to handle this. Any glyph can be made a mark glyph.

Make an example .glyphs file, a failing test, and fix.

**Comment by anthrotype** [comment]
this is already supported with https://github.com/googlefonts/fontc/pull/777
