### ISSUE TITLE
Trying to figure out how to use VariationModel

### ISSUE THREAD

**Issue by cmyr** [googlefonts/fontc#354]
This is a dump of my thoughts on trying to get deltas into fea-rs. I've spent a bunch of time in the variations code in fontir, and I have some ideas, but I'm not sure how much sense they make, so I want to take this opportunity to rubber-ducky a little bit.

- In general terms, I can imagine two different approaches to getting the delta values into fea-rs. The simplest* is something where there is some sort of 'delta provider' type passed in by the compiler, which is a blackbox that is given some set of locations + values, and returns deltas. This is a nice separation of concerns, but it has the significant downside that (for instance) fea-rs can not compile variable fea without being hooked up to the compiler. The alternative is to have some rust equivalent of varLib, which fea-rs can use directly. This is maybe the best path, but it would require some rethinking of the current API.
- currently, there is a single VariationModel for the whole font. In fea-rs, each individual metric in a value record might be variable, and each one specifies its own location set. This means that I potentially need a new VariationModel for each metric. In practice, these will often be identical, and given that they are expensive to construct I would expect us to cache them somewhere.
- This would not be trivial to do in the current implementation; the obvious key to this cache is the locationset, but the locationset is mutated during sorting (and the sorting is the expensive part) so we would also need some way (an additional cache, presumably) of mapping locationsets to their canonical representations.

Given all this, my current feeling is that the VariationModel code should be reworked a little bit to become slightly more 'modal'. That is, I think it should probably be broken up into steps, like

- first you create something like a `VariationSpace`, that only has the font's axis info
- this type has a method, `normalized_location_set` that takes an arbitrary location set, and finds the (cached) normalized equivalent
- this normalized set gets passed to some function that gets the cached model for that location set, building it if necessary
- *this* type is the thing that computes the deltas.

Steps 2 & 3 could probably be combined?

## an aside on python vs rust idioms/style

iirc, the variationmodel code is a pretty direct port of the implementation in python, and it's been really informative to me in terms of thinking about the kinds of programs that python pushes you to write, and how that is different from what we might do in rust.

One major example here is that python tends to expect a function to be called with various inputs, and to be very defensive in input handling. A specific example of this here is how in various places we sanitize the input locations, removing unknown axes, and inserting missing axes. In rust, I would prefer an approach where there is a single step that creates a normalized location from some user position, and that this step ensures that tags exist and that all tags have entries; then when we have a normalizedlocation that we can confidently use with the model.

I think what I'm really trying to push for, here, is *invariant oriented programming*; being more explicit and more constrained in these methods about what exactly the inputs are, and then providing simple methods that guarantee to the user that they are meeting the constraints.

Anyway: this ultimately might not matter, but I wanted to do a briandump while I was thinking about this.

**Comment by rsheeter** [comment]
> This means that I potentially need a new VariationModel for each metric

In Python there is a step to create a "narrower" variation model, much as you seem to describe here, that happens in production of things like gvar. In Rust I sought to avoid it. I don't _think_ you should need to either.

> The simplest* is something where there is some sort of 'delta provider' type passed in by the compiler

> The alternative is to have some rust equivalent of varLib, which fea-rs can use directly

I agree with both points. I propose we start with fea-rs accepting a delta provider. After I implement that satisfactorily that can inform the migration of variation.rs to, I would guess, fontdrasil and the adaptation of APIs to let fea-rs consume it directly. 

> python tends to expect a function to be called with various inputs, and to be very defensive in input handling

I don't think I agree. If anything I perceive the opposite: Rust tends to have specific detailed error handling - which is great! - whereas Python is wont to assume everything is great and then crash when it isn't. If it quacks like a duck but 30 layers deep it turns out not to have a beak ... kaboom.

> when we have a normalizedlocation that we can confidently use with the model

This implies that type is produced or validated/blessed by the variation model, likely enforced by way of additional types. Naively that seems like it forces an additional interaction that is just a nuisance?

**Comment by rsheeter** [comment]
> the variationmodel code is a pretty direct port of the implementation in python

For context this is intentionally true, it makes figuring out why they diverge when they diverge *much* easier.

**Comment by rsheeter** [comment]
We are getting variation values into fea-rs now so I think this is done?
