### ISSUE TITLE
Check for `From<&Thing>` and remove if cloning

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontc#363]
See https://github.com/googlefonts/fontc/pull/359#discussion_r1252428339

**Comment by rictic** [comment]
Did a quick pass over all of the `From<&` implementations in fontations and fontc, and each was either copying the reference or was just copying some Copy values out of the reference. Someone else should probably double check, but I couldn't find any work needed for this issue.

**Comment by rsheeter** [comment]
That seems good enough to close to me. Worst case if we find one hiding somewhere it's easy enough to fix.
