### ISSUE TITLE
Try just storing glyf/loca together

### ISSUE THREAD

**Issue by cmyr** [googlefonts/fontc#397]
These have always been annoying since the format lives outside of both of them, but if we can bundle this all up into one object for the sake of persistence that should be an improvement.

> Given that we compute them together I think this might make more sense and might be a better change. Want to try that?

_Originally posted by @rsheeter in https://github.com/googlefonts/fontc/pull/383#discussion_r1290732042_

**Comment by cmyr** [comment]
Playing around with this and it's annoying, because of how assembling the font expects each table to exist on disk in its final representation. This would either require special-casing glyf/loca, or adding additional work tasks that take our unified glyf/loca and then splits it out again, which sort of defeats the point..

**Comment by rsheeter** [comment]
^ sounds fairly convincing wrt this not being a significant win.
