### ISSUE TITLE
should we compute IUP optimized deltas also for composite glyphs?

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/fontc#398]
the OT spec says:

https://learn.microsoft.com/en-us/typography/opentype/spec/gvar#inferred-deltas-for-un-referenced-point-numbers

> Note: inferring of deltas for un-referenced points applies only to simple glyphs, not to composite glyphs.

And fontc, currently does not process the composite glyphs through `iup_delta_optimize`:

https://github.com/googlefonts/fontc/blob/cfd11e2ff32ab50259fb5f582d514ade66273b7f/fontbe/src/glyphs.rs#L344

https://github.com/googlefonts/fontc/blob/cfd11e2ff32ab50259fb5f582d514ade66273b7f/fontbe/src/glyphs.rs#L600-L606

However, fonttools varLib _does_ process the composite glyphs through its `iup_delta_optimize`, the deltas and origCoords arrays contain one (x,y) for each component and it treats each component as a distinct "contour" in the endPts list, see `_getCoordinatesAndControls` method of glyf table, as used in varLib.build:

https://github.com/fonttools/fonttools/blob/dd783ff95e97e020bf6a4215a20ea11707174f38/Lib/fontTools/ttLib/tables/_g_l_y_f.py#L400-L412
https://github.com/fonttools/fonttools/blob/dd783ff95e97e020bf6a4215a20ea11707174f38/Lib/fontTools/varLib/__init__.py#L354-L357

Because of this discrepancy between fonttools and fontc, we get the following diffs when comparing the gvar of e.g. Oswald-VF.ttf for composite glyphs such as "A-cy" and others (note how in fonttools output, the (0,0) deltas are omitted, i.e. inferred):

```diff
--- Oswald-VF-fontmake.ttf
+++ Oswald-VF-fontc.ttf
     <glyphVariations glyph="A-cy">
       <tuple>
         <coord axis="wght" value="-1.0"/>
+        <delta pt="0" x="0" y="0"/>
+        <delta pt="1" x="0" y="0"/>
         <delta pt="2" x="-24" y="0"/>
+        <delta pt="3" x="0" y="0"/>
+        <delta pt="4" x="0" y="0"/>
       </tuple>
```

Question: should we match the fonttools output and therefore also include composites in the iup_delta_optimization, despite what the spec says about inferred deltas only applying to simple glyphs? I suppose yes but maybe @behdad has more insights into this.

**Comment by anthrotype** [comment]
> IUP does not apply to them

but fonttools does consider them when doing iup_delta_optimize... (fontc does not at the moment, hence I raised the question)

**Comment by anthrotype** [comment]
https://learn.microsoft.com/en-us/typography/opentype/spec/gvar#point-numbers-and-processing-for-composite-glyphs

> The adjustment deltas for component glyphs adjust the placement of the component. If a glyph component is not referenced in the packed point numbers, then its position is not adjusted

I suppose the above quote from the gvar spec describes this situation whereby a (0, 0) placement adjustment for a component can be omitted/implied from the composite glyph's gvar entry, and that's what fonttools varLib does (whereas fontc always emits (0,0) for components whose placement does not vary).

In fonttools this is performed within the same iup_delta_optimize routine, so in this sense IUP does apply to composites, although in a limited fashion?

**Comment by behdad** [comment]
Yes. It only does drop them if they are zero. Otherwise, the `iup_contour_optimize` just returns if num points in the contour is 1 (as is the case for composites):
```
    n = len(deltas) 
 
    # Get the easy cases out of the way: 
 
    # If all are within tolerance distance of 0, encode nothing: 
    if all(abs(complex(*p)) <= tolerance for p in deltas): 
        return [None] * n 
 
    # If there's exactly one point, return it: 
    if n == 1: 
        return deltas 
```

**Comment by rsheeter** [comment]
Maybe we should handle it but not via iup? - it's a bit counterintuitive to do that when iup doesn't apply.

**Comment by behdad** [comment]
> Maybe we should handle it but not via iup? - it's a bit counterintuitive to do that when iup doesn't apply.

Fair. Maybe we should also fix fonttools to still do it if IUP is disabled.
