### ISSUE TITLE
incorrect feature deltas when sparse

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontc#407]
As noted in https://github.com/googlefonts/fontc/pull/373#discussion_r1299409825, #373 will have the same problem as #400 for kerning.

**Comment by anthrotype** [comment]
the same or equivalent patch as above should be applied to the `resolve_variable_metric` standalone function, which is the one used for the autogenerated kern/mark which we care the most

**Comment by anthrotype** [comment]
Fixed by #779
