### ISSUE TITLE
Support .glyphspackage format

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/fontc#435]
prior art:

https://github.com/googlefonts/glyphsLib/blob/8c0157e4fba7a97fc9fbd4e4b532bcf92796c06f/Lib/glyphsLib/parser.py#L103-L140

https://github.com/florianpircher/glyphspack (in rust)

https://forum.glyphsapp.com/t/documentation-on-the-glyphspackage-format/23435

**Comment by rsheeter** [comment]
All our v2 == v3 tests should be updated to say content loaded from v2.glyphs, v2.glyphspackage, v3.glyphs, v3.glyphspackage matches.
