### ISSUE TITLE
include requirements.txt for bundled python scripts?

### ISSUE THREAD

**Issue by cmyr** [googlefonts/fontc#442]
Trying to use the ttx_diff script for the first time and have no idea what deps I need to install.

**Comment by anthrotype** [comment]
yeah, I had the same issue, +1 on adding a requirements.txt file. Looking at the imports, I think we need at least the following:

```
absl-py
lxml
fontTools
```

**Comment by anthrotype** [comment]
oh and `fontmake` itself, of course
