### ISSUE TITLE
Improve onboarding in readme

### ISSUE THREAD

**Issue by schriftgestalt** [googlefonts/fontc#445]
As someone unfamiliar with rust and fontc, I would need some help getting started. Are there and how to get precompiled binaries? How to do a local debug build?

**Comment by anthrotype** [comment]
no precompiled binaries yet. I'd start with installing the rust toolchain (https://www.rust-lang.org/learn/get-started) and then run `cargo build` (for default debug build) or `cargo build --release`, then you'll find the binaries in either target/debug or target/release sub-directories. `cargo run -p fontc -- [fontc options]` will rebuild and run fontc at the same time.

**Comment by schriftgestalt** [comment]
Can you put that into the readme?

**Comment by rsheeter** [comment]
Pardon the delay, was out for TPAC. Does https://github.com/googlefonts/fontc/pull/455 help?

**Comment by rsheeter** [comment]
Closing, please reopen if it's still hard to get started.
