### ISSUE TITLE
fontc produces no-op avar even when axes define no mappings

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/fontc#469]
When a source file contains no axis mappings (thus user-space and design-space locations are meant to be identical and no "warping" occurs), e.g. this simple single-axis font:

```xml
<designspace format="5.0">
  <axes>
    <axis tag="wght" name="Weight" minimum="400" maximum="700" default="400"/>
  </axes>
```

... then fontc insists on building an avar table even when this does not do anything interesting besides the default {-1.0: -1.0, 0.0: 0.0, 1.0: 1.0} mappings, i.e. `ttx -t avar -q -o - build/font.ttf` gives:

```xml
  <avar>
    <version major="1" minor="0"/>
    <segment axis="wght">
      <mapping from="-1.0" to="-1.0"/>
      <mapping from="0.0" to="0.0"/>
      <mapping from="1.0" to="1.0"/>
    </segment>
  </avar>
```

FontTools in cases like this omits building an avar table, so we should match it.

**Comment by anthrotype** [comment]
specifically this:

https://github.com/fonttools/fonttools/blob/0a3360e52727cdefce2e9b28286b074faf99033c/Lib/fontTools/varLib/__init__.py#L204-L206C9

**Comment by rsheeter** [comment]
Good catch!
