### ISSUE TITLE
default cu2qu tolerance should be relative to UPEM

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/fontc#474]
fontTools.cu2qu.ufo.fonts_to_quadratic (used by fontmake via ufo2ft.preProcessor) defaults to a relative maximum error of 0.001 * font.info.unitsPerEm, which works out as 1.0 absolute font units for fonts with UPEM=1000 as it's more frequently the case in font editors.

fontc cubics_to_quadratics method currently defaults to 1.0 as the absolute tolerace, which only matches fontmake/fonttools when the input source has UPEM 1000; if UPEM is larger, fontc' default tolerance is too fine grained (leading to more quad control points), if UPEM is smaller, the default tolerance is too coarse, not precise enough.

So we want to match fontmake default tolerance by making it 1/1000th of the UPEM.

fontmake also has an option to control the cu2qu --conversion-error which I believe is rarely used (note, unlike the default error, this optional one is actually measured in absolute font units), we may want to add a similar flag to fontc.

**Comment by rsheeter** [comment]
+1 to making it computed. I hope we can avoid adding a flag if the default is good.
