### ISSUE TITLE
Did we pointlessly overcomplicate our serde?

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontc#495]
Why for serde do you have near-identical copies of structs (e.g. StaticMetadata(SerdeRepr)), instead of using custom (de)serialization logic on specific fields you want to handle differently? It gives a first impression of a fair bit of redundancy and boilerplate, how did it come about and can a more elegant solution be used.

**Comment by rsheeter** [comment]
How it came about is that we wanted to write both text and binary versions of things and some of our types were imploding at least one of the serde implementations. I think we flipped at least one of the serde libraries we use from toml => yaml so it is possible some of our serde impls are no longer required.

**Comment by cmyr** [comment]
This has now been significantly simplified.

**Comment by rsheeter** [comment]
Report and fix most appreciated :)
