### ISSUE TITLE
setup publishing workflow

### ISSUE THREAD

**Issue by cmyr** [googlefonts/fontc#504]
as we're going to make fea-rs depend on fontdrasil, we'll also have to start publishing that crate.

For simplicity we should follow the same workflow used in fontations, which means adding `bump_version.sh` and `release.sh`, and then also marking all the non-fontdrasil crates as no-release (or whatever the cargo manifest flag is, I forget offhand.)

also we should probably bump fontdrasil to 0.1.0 before hand.

**Comment by rsheeter** [comment]
+1. Let's publish fontc itself too.

**Comment by cmyr** [comment]
publishing fontc means publishing everything, since it depends on everything. We can definitely do that but I'd personally prefer putting it off for a while, since it's another ongoing chore.


Actually the situation is now kind of annoying; if we ever break font-types and want to update fontc, we need to:

- publish fontations
- update & publish fontdrasil
- update & publish fea-rs
- update & publish the rest of the fontc crates

so... not the end of the world, but kind of annoying.


One thing we could consider is moving `fea-rs` into this repo?

**Comment by anthrotype** [comment]
> One thing we could consider is moving fea-rs into this repo?

big +1 on that

**Comment by cmyr** [comment]
yea the more I think about it the more sense it makes, it also means we can get away without publishing any new crates for the time being, if we so wish.

**Comment by rsheeter** [comment]
+1 to fea-rs => here. I do think we should publish fontc in the not too distant future just to grab the names.

**Comment by cmyr** [comment]
publishing workflow was setup in #795 and #826
