### ISSUE TITLE
[fea-rs] Early kern rules should override later ones, not the other way around

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontc#550]
I found a difference in shaping between fonttools and fea-rs which I narrowed down to the processing of `enum pos` rules. The following feature file:

```fea
feature kern {
    pos A B 100;
    enum pos A B -50;
} kern;
```

produces different results in feaLib and fea-rs.

 FontTools:

```xml
      <Lookup index="0">
        <LookupType value="2"/>
        <LookupFlag value="0"/>
        <!-- SubTableCount=1 -->
        <PairPos index="0" Format="1">
          <Coverage>
            <Glyph value="A"/>
          </Coverage>
          <ValueFormat1 value="4"/>
          <ValueFormat2 value="0"/>
          <!-- PairSetCount=1 -->
          <PairSet index="0">
            <!-- PairValueCount=1 -->
            <PairValueRecord index="0">
              <SecondGlyph value="B"/>
              <Value1 XAdvance="100"/>
            </PairValueRecord>
          </PairSet>
        </PairPos>
      </Lookup>
```

fea-rs:

```xml
      <Lookup index="0">
        <LookupType value="2"/>
        <LookupFlag value="0"/>
        <!-- SubTableCount=1 -->
        <PairPos index="0" Format="1">
          <Coverage>
            <Glyph value="A"/>
          </Coverage>
          <ValueFormat1 value="4"/>
          <ValueFormat2 value="0"/>
          <!-- PairSetCount=1 -->
          <PairSet index="0">
            <!-- PairValueCount=1 -->
            <PairValueRecord index="0">
              <SecondGlyph value="B"/>
              <Value1 XAdvance="-50"/>
            </PairValueRecord>
          </PairSet>
        </PairPos>
      </Lookup>
```

This is because, according to the spec,

> Specific pairs generated by an enum rule may be overridden by specifying preceding single pairs. Because of this case, it is not an error when specific kern pairs conflict because they have the same glyphs. **When specific kern pair rules conflict, the first rule specified is used, and later conflicting rule are skipped.**

**Comment by anthrotype** [comment]
Thank you. This situation should probably be handled in fea-rs rather than fontc' kern feature generator as it affects both hand-written FEA and code-generated pos rules.

**Comment by simoncozens** [comment]
Seems good on the whole font too. Nice, I can now compile Very Complex Secret Font in six seconds instead of eight and get comparable results...

**Comment by anthrotype** [comment]
cool thanks

> six seconds instead of eight

eight seconds?

**Comment by simoncozens** [comment]
Yes.

**Comment by anthrotype** [comment]
a bit underwhelming. Can you try with --emit-ir=false?

**Comment by simoncozens** [comment]
(This is using fontmake, but replacing the line `from fontTools.feaLib.builder import addOpenTypeFeaturesFromString` in ufo2ft.featureCompiler with `from notabug import addOpenTypeFeaturesFromString`, where notabug is a Python wrapper around fea-rs.)

**Comment by simoncozens** [comment]
Oh, I'm not using fontc, because we have stuff like Glyphs contextual mark positioning, which I presume is not supported yet.

**Comment by anthrotype** [comment]
gotcha

**Comment by anthrotype** [comment]
> https://github.com/googlefonts/fontc/issues/551

not yet, filed https://github.com/googlefonts/fontc/issues/551
