### ISSUE TITLE
Move fontc tests from lib.rs into /tests?

### ISSUE THREAD

**Issue by cmyr** [googlefonts/fontc#585]
> Also as a general observation (not having really looked at this in much detail before) a bunch(/most/all?) of the tests in `lib.rs` really feel like integration tests, which can potentially live outside of the crate in the `tests` directory, assuming that they don't need to access much private internal API. I will put this on my 'one day' todo list...

_Originally posted by @cmyr in https://github.com/googlefonts/fontc/issues/584#issuecomment-1817198893_

**Comment by rsheeter** [comment]
What is the advantage of making this change?

**Comment by cmyr** [comment]
The main motivation for me was that `lib.rs` is pushing 3k lines and is only going to get larger, and I was noticing my IDE start to slow down a bit when navigating the file. The other motivation is something I apparently had backwards; I had a vague memory that 'integration' tests were compiled differently and this had advantages, but [apparently this actually has disadvantages](https://matklad.github.io/2021/02/27/delete-cargo-integration-tests.html)?

One other advantage (which I'm not sure is important) is that integration tests cannot use private API, which is sometimes helpful.

**Comment by rsheeter** [comment]
It's not particularly a goal for these to avoid private APIs. Would splitting lib.rs up w/o moving it to /tests help wrt IDE slowdown?

**Comment by cmyr** [comment]
yes that would be fine but I don't think it's pressing. Will close this, we can split up the tests if it gets more annoying.
