### ISSUE TITLE
Port fonttools optimized PairPos subtable splitting?

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/fontc#612]
@belluzj wrote in https://github.com/googlefonts/fontc/issues/610#issuecomment-1831650350

> you may benefit from translating to Rust the GPOS compaction from here: https://github.com/fonttools/fonttools/pull/2326. It's not super slow even though it's Python, so it might be fast enough in Rust, and it doesn't need to know about the glyph's Unicode properties (so no need for GSUB closure) in order to decide how to split the subtables, it does so only by looking at the filled-in/empty areas of the matrices. Let me know if you have any questions.

The code is here:
https://github.com/fonttools/fonttools/blob/main/Lib/fontTools/otlLib/optimize/gpos.py

It can be enabled by setting a config option on a TTFont before compiling, takes numbers from 0 (disabled by default) to 9:
https://github.com/fonttools/fonttools/blob/2b115eaae83dddb2638b079c7e88bda2e94cd6f9/Lib/fontTools/config/__init__.py#L25-L37
```python
font = TTFont(...)
font.cfg["fontTools.otlLib.optimize.gpos:COMPRESSION_LEVEL"] = 9
font.save(...)
```

It's also possible to run as CLI on existing font file with `fonttools otlLib.optimize --help`

**Comment by anthrotype** [comment]
actually, we would still need to do the GSUB closure regardless, because of the need to separate the LTR from the RTL kerning pairs (each requires a different kind of value record).
So maybe it's not worth implementing this. IIRC, there weren't much file size gains from doing _both_ the split-by-script kerning _and_ the optimized GPOS compaction as most of the sparseness came from non-interacting cross-script areas of the pairpos matrices. 
/cc @belluzj @madig

**Comment by rsheeter** [comment]
Based on ^ I will close. Please reopen if there is reason to believe that there are file size benefits remaining even after doing split-by-script.
