### ISSUE TITLE
Layout-normalizer: does not handle extension lookups

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontc#641]
```
% wget https://notofonts.github.io/latin-greek-cyrillic/fonts/NotoSans/unhinted/ttf/NotoSans-Regular.ttf
% layout-normalizer -t GPOS NotoSans-Regular.ttf | grep Mark
# 8686 MarkToBase rules
# 8686 MarkToBase rules
# 8686 MarkToBase rules
# 8686 MarkToBase rules
# 8686 MarkToBase rules
# 415 MarkToMark rules
# 415 MarkToMark rules
# 415 MarkToMark rules
# 415 MarkToMark rules
# 415 MarkToMark rules
```

```
% wget "https://notofonts.github.io/latin-greek-cyrillic/fonts/NotoSans/unhinted/variable/NotoSans[wdth,wght].ttf"
%  layout-normalizer -t GPOS NotoSans\[wdth,wght\].ttf | grep Mark
# 415 MarkToMark rules
# 415 MarkToMark rules
# 415 MarkToMark rules
# 415 MarkToMark rules
# 415 MarkToMark rules
# 415 MarkToMark rules
# 415 MarkToMark rules
# 415 MarkToMark rules
# 415 MarkToMark rules
# 415 MarkToMark rules
# 415 MarkToMark rules
# 415 MarkToMark rules
# 415 MarkToMark rules
# 415 MarkToMark rules
# 415 MarkToMark rules
```

**Comment by simoncozens** [comment]
Doesn't happen in all fonts; I can't find an example in a small font, but it seems to happen in large fonts with multiple languagesystems.

I strongly recommend dumping the lookups in the order they are stored in the lookup list, then dumping a map of the languagesystems->lookup IDs. Much less duplication that way, too.

**Comment by anthrotype** [comment]
I suspect layout-normalizer is not handling extension lookups properly

**Comment by rsheeter** [comment]
> we are basically discarding lookup order

We want the compare semantically equivalent things as equal. I don't think we can reach the end goal while completely ignoring lookup order, we have to interpret it when building the output. I entirely understand ignoring it entirely as a starting point but my guess is we'll have to change that at some point. Baby steps :)

> ignoring lookup IDs/order makes it very difficult to track back into the original table and work out where the rules are coming from. But as you say that's maybe a different use case

Naively, perhaps we might optionally output debug information separate of the normalized representation?

**Comment by simoncozens** [comment]
> Naively, perhaps we might optionally output debug information separate of the normalized representation?

I think it would be very useful to support different levels of "normalization":

* dumping rules from individual subtables in order
* dumping rules from individual lookups in order
* dumping rules from features

**Comment by cmyr** [comment]
@simoncozens can you clarify the distinction between 'individual subtables' and 'individual lookups'? the first two feel very similar to me: basically a version that more intentionally preserves lookup order. Would the first one just mean printing explicit subtable information? Because the order of rules in a lookup should just be the concatenation of the rules in each subtable?

**Comment by simoncozens** [comment]
> Because the order of rules in a lookup should just be the concatenation of the rules in each subtable?

Well, this depends on how much "interpreting" you're doing - your goal above was to provide a "view" into the data, ignoring subtables and lookups, i.e. to list out the *effect* of the rules, what the rules mean. At level 1, you would want a distinction between

```
pos [A B C] [D E F] 20; # PairPos 2 class
```

and

```
pos A D 20;
pos A E 20;
pos A F 20;
```

At level 2, they "mean" the same.
