### ISSUE TITLE
.glyphs Axis Mapping interpretation

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontc#65]
https://github.com/googlefonts/glyphsLib/issues/745 challenges the assertion that .glyphs Axis Mappings are in the form `user = design`. However, glyphsLib has long interpreted it the other way around as described in https://github.com/googlefonts/glyphsLib/issues/745#issuecomment-1357651512. That means:

* Any existing project that delivers with fontmake is clearly interpreting it the way glphsLib does today.
* Any new project that will deliver with fontmake will too.
* Only a .glyphs file that isn't for use with GF will do it the other way around.

Furthermore, if a font has a weight axis we can warn if it "looks backwards," e.g. user is not hundred-weights and design is, and perhaps offer a flag to flip the interpretation.

**Comment by anthrotype** [comment]
Apparently Glyphs 3.2 now interprets the axis mappings in the same way as fontmake, see

https://github.com/googlefonts/glyphsLib/issues/745#issuecomment-1380367686

I suppose that means we can keep it as it is :)

**Comment by rsheeter** [comment]
To be sure I'm remembering this right,  we're the only ones who ever used it and we used it - from Glyphs pov - backwards so now Glyphs has flipped it we're fine to just keep treating it the way we always did? - assuming that's right I agree, we can close.
