### ISSUE TITLE
layout-normalizer: figure out a testing strategy

### ISSUE THREAD

**Issue by cmyr** [googlefonts/fontc#657]
> I'm trying to think of how to write tests in a way that is meaningful. It would be relatively easy to write something that took a known font, loaded it, and then asserted that we had the correct number of lookups of the relevant type, for instance, but that doesn't seem _super_ useful. In the general case we want to check that our transformations make sense (e.g. that we are skipping rules in subtables correctly, or not) and this is tricky. The most reasonable & useful approach I can think of is that we could use write-fonts and compile specific small examples, and then verify our behaviour against these.

I'm going to open a separate issue to figure out how best to start testing here, since it feels like this tool is sort of developing a life of its own. More generally the way a lot of this code has been written so far was with the intention of just doing a single simple representation, and I think we've sort of generally agreed that it would be useful if it could work in different modes, which means that I need to use a more flexible representation (currently I'm basically transforming everything into a final representation in the first pass)

_Originally posted by @cmyr in https://github.com/googlefonts/fontc/issues/654#issuecomment-1856172170_

**Comment by rsheeter** [comment]
I suggest we separate this into two issues. We definitely want to test it, this issue can cover that. Supporting multiple representations is nice to have, feels like it makes sense, but it is not our primary goal. I'd give that it's own issue and treat it as lower priority.

**Comment by cmyr** [comment]
I mention them in the same breath only because implementing some of the behaviour we want to test (like how we merge overlapping rules in different lookups) will (I think!) require us to change how we are storing rules internally.
