### ISSUE TITLE
fontc should accept standalone UFO as input and build static font from it

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/fontc#713]
currently it requires a no-op (single-master) .designspace file input in order to build a static font from a single UFO source (see resources/testdata/static.designspace).
It should instead accept the .ufo as input and maybe wrap that in a single-source .designspace if need be without requiring user to do that

**Comment by cmyr** [comment]
Agree, I've wanted this at various points in the past and been surprised it didn't work.
