### ISSUE TITLE
[layout-normalizer] Font->glyph name mapping incomplete and at wrong level

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontc#787]
To provide human-readable output, layout-normalizer maps glyph IDs to glyph names. It does this purely by looking at codepoints and turning codepoints into glyph names using the AGL, defaulting to stringifying the GID for unencoded glyphs. The first place to look for glyph names should be the `post` table's `glyphNameIndex`, and then potentially the *Macintosh* glyph list (See the [`post` table spec](https://learn.microsoft.com/en-us/typography/opentype/spec/post)), and if there isn't one there, then stringify the GID. (I don't recommend intuiting a glyph name from the cmap table.)

Perhaps `read_fonts::tables::post::Post::glyph_name` would be helpful here; and perhaps some mid-level font library (Skrifa?) should have a utility function that maps a glyph ID to `post` name if there is one and stringifying the GID if not.

**Comment by simoncozens** [comment]
This appears to do the job:

```rust
fn gid_to_name<'a>(font: &impl TableProvider<'a>, gid: GlyphId) -> String {
    if let Ok(Some(name)) = font
        .post()
        .map(|post| post.glyph_name(gid).map(|x| x.to_string()))
    {
        name
    } else {
        format!("gid{:}", gid)
    }
}
```

**Comment by cmyr** [comment]
good call, not sure why I didn't bother checking `post` first, definitely an oversight.
