### ISSUE TITLE
Glyph order not deterministic if not explicitly given

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontc#814]
If I compile from a .designspace project, and there is no explicit glyph order defined in the sources, the generated glyph order seems random, and is different in each run.

Suggest to sort by glyph name in that case.

**Comment by rsheeter** [comment]
That's a bug, ty for reporting.

**Comment by anthrotype** [comment]
Sort alphabetically but keep .notdef as first gid0 like ufo2ft does
