### ISSUE TITLE
.glyphs parsing failures

### ISSUE THREAD

**Issue by cmyr** [googlefonts/fontc#851]
After running fontc on ~480 fonts hosted by google fonts, a full ~100 of them failed to compile due to errors while parsing .glyphs files.

- the majority of these (74) relate to unknown/legacy glyph categories, like "Uppercase" and "Smallcaps" (which I think are now subcategories?) As well as "Other" (which we should parse?) and the empty string, which we should treat as no category.
- 21 of these are "Oops this parser is just broken"
- 2 of these are 'unexpected character' during parsing
- 1 of these is 'Unknown escape code'.

so the first of these should be easy enough to solve, and the others are tbd (but I'm optimistic)

**Comment by rsheeter** [comment]
Two requests:

1) Document how to run on lots of fonts on the root index, it's a useful tool
2) Capture specific examples, e.g. clone this repo and build this file. Ideally the crater-esque run would report that.

**Comment by rsheeter** [comment]
Did you happen to run ttx_diff on the ~380 that did compile? - would be very interested in our starting position for both how many compile and how many pass so we can see the improvement over time.

**Comment by cmyr** [comment]
these were all resolved a while ago
