### ISSUE TITLE
non-master Glyphs layers without attributes should be ignored

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontc#878]
Designers may use Glyphs "layers" for various purposes - backup, testing, etc. - this creates layers in the Glyphs sources which are not associated with a known master. It's totally fine for a Glyphs layer to have an layerId which is not the id of a known master. (These appear as regular, not bold, in the glyphs layers list.)

Currently fontc errors if a layer has no associated master:

```
[2024-07-23T19:26:07.320205Z ThreadId(1) fontc::workload ERROR] Fe(Glyph([redacted])) failed No master [also redacted] exists. Referenced by glyph [redacted].
```

**Comment by cmyr** [comment]
okay, thanks for the explanation. I'm currently working through a bunch of glyphs compiler errors so will hope to get to this shortly.

**Comment by anthrotype** [comment]
just a little clarification, as I was initially confused by the title of this issue mentioning "layers which don't have an associated master". As you know, all Glyphs layers have both a `layerId` and an `associatedMasterId` attributes. For "master" layers (layers which _directly_ correspond to a given font-wide master), the `layerId == associatedMasterId`, in which case the latter is omitted in the .glyphs file; other non-master layers have a `layerId != associatedMasterId`, the latter being the id of the font master that layer is indirectly associated with (they appear nested below it in the UI). In this sense, technically there are no layers without an associatedMasterId. New layers' name (initially the current timestamp) appears in regular, non-bold, font initially after they are first created, and always fall below some the currently selected master layer (the latter's layerId becomes their associatedMasterId); these layers can be used, as @simoncozens said, for backup or testing purposes, in which case can be simply ignored when compiling.
But as soon as they gain any additional `attributes` (as one right clicks on them) these non-master layers can become either intermediate layers or alternate layers or various colorful layers (or all of them at the same time), and should not be ignored but handled correctly. See https://github.com/googlefonts/fontc/issues/62#issuecomment-1354776035

I think we currently only support intermediate (aka "brace") layers, but not the alternate ("bracket") layers (https://github.com/googlefonts/fontc/issues/533), nor any of the colored ones.

**Comment by anthrotype** [comment]
I suggest to rename this "non-master Glyphs layers without attributes should be ignored"

**Comment by anthrotype** [comment]
Also I'd like to stress this, in case it wasn't clear, if a .glyphs source omits the associatedMasterId attribute, it is assumed that the latter defaults to its layerId (which is required non optional attribute); thus, only master layers (i.e. layers directly corresponding to a font master, and whose layerId is among the font master's set of ids) have no associatedMasterId explicitly set. If a .glyphs file contains a layer where the associatedMasterId is omitted and its layerId does not correspond to any of the font masters, or the associatedMasterId points to a font master which is not present, then the source is in a bad state and contains an invalid layer, I don't think it's possible to create such invalid layers from the font editor's UI, one would have to hack the .glyphs source text by hand. These invalid layers should produce an compile error, if it isn't the case already.

**Comment by rsheeter** [comment]
Can we get specific steps to reproduce (e.g. do x,y,z in glyphs) or a sample source with the problem? - when I quickly tried adding a scratch layer (not-bold in the ui) to a test font it didn't seem to leave me in a state that crashed fontc. The layer in question does have an associated master id and I wasn't immediately able to produce a file that didn't via the Glyphs UI.

**Comment by anthrotype** [comment]
by the way, glyphs-reader already skips "draft" layers here:

https://github.com/googlefonts/fontc/blob/3d7a5892cab7320d16292e74faf42a02904806d2/glyphs-reader/src/font.rs#L649-L656

https://github.com/googlefonts/fontc/blob/3d7a5892cab7320d16292e74faf42a02904806d2/glyphs-reader/src/font.rs#L1757-L1760

> The layer in question does have an associated master id

yeah, as I said, _all_ layers belong to some master, either by being themselves directly a master layer or by having their associatedMasterId point to one of the existing masters.

**Comment by rsheeter** [comment]
I still don't know what "without attributes" concretely means - what attributes? - or how to reproduce any specific problem?

**Comment by rsheeter** [comment]
Closing, please reopen or file a new bug if there is yet something that kerplodes us.
