### ISSUE TITLE
new clippy complains about docstrings containing unescaped snippets of python

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/fontc#940]
https://github.com/googlefonts/fontc/blob/87729c1a0780885131bf0e18d7afa335babfa8d5/fontir/src/variations.rs#L809-L816

e.g. see https://github.com/googlefonts/fontc/actions/runs/10725483180/job/29743404967?pr=939

should we simply remove one `/` and keep these as inline comments instead of `///` proper formatted docstring. They only appear inside tests, not sure what the use of `///` docstrings for test methods

**Comment by rsheeter** [comment]
Fixed by #941
