### ISSUE TITLE
Consider size in crater

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontc#972]
@garretrieger suggested adding size to https://googlefonts.github.io/fontc_crater/, e.g. if ours is dramatically larger (say more than +10%?) deem it a fail, based on past experience with HarfBuzz vs FontTools subsetting comparisons

**Comment by rsheeter** [comment]
Possibly on a table by table basis as one table being more compact shouldn't hide another table being bigger

**Comment by cmyr** [comment]
I agree this is something it would be nice to know, and it's maybe mostly a question of UX? A first step would be to add some size comparison functionality to ttx_diff.

**Comment by cmyr** [comment]
added in #1100
